### ISSUE TITLE
Add documentation for match_msd()

### ISSUE THREAD

**Issue by achafetz** [ICPI/ICPIutilities#15]
new function `match_msd()` now added to package (#14). Function is used to match DATIM Genie output to MSD format. Need documentation around new function into README

FYI @kschlenker @jaliasd 

Function 
  - strips out `dataElementUID`, `categoryOptionComboUID`, `ApprovalLevel`, and `ApprovalLevelDescription`
  - add in APR value for FY2017
  - export as Rds
  - default is to output lower case, but can be left as camel case

**Comment by achafetz** [comment]
@HoustonJamie FYI, here is the function brought up during the all staff

**Comment by HoustonJamie** [comment]
Thanks!

Sent from my iPhone

On Aug 27, 2018, at 11:19 AM, Aaron <notifications@github.com<mailto:notifications@github.com>> wrote:


@HoustonJamie<https://github.com/HoustonJamie> FYI, here is the function brought up during the all staff

**Comment by achafetz** [comment]
Documentation now added to the [README](https://github.com/ICPI/ICPIutilities#match_msd)
