### ISSUE TITLE
Abort DATIM API call?

### ISSUE THREAD

**Issue by achafetz** [ICPI/ICPIutilities#22]
@jason-p-pickering, I do an API call to pull down the singular mechanism/partner name from DATIM via `rename_official()` ([info](https://github.com/ICPI/ICPIutilities#rename_official)/[code](https://github.com/ICPI/ICPIutilities/blob/master/R/rename_official.R)). 

This function is used in other functions and can be an issue if say, DATIM is down for updating or there is no internet connectivity.

How would I write an IF statement at the begging of the function to check if R can access the page, otherwise it will abort, so the rest of the code can run?

```
  #check access
  if([no access]) {
    stop()
  }
```

Pulling down the SQL view
https://github.com/ICPI/ICPIutilities/blob/6069ee20de10b70540d131cec30be4981044e845/R/rename_official.R#L27-L29

**Comment by jason-p-pickering** [comment]
@achafetz I would suggest that you check the HTTP response code. Check here for a clue

https://github.com/jason-p-pickering/datim-validation/blob/master/R/getDataElementMap.R#L14-L15

You should received a 200 for a successful response, otherwise, there is an error.

**Comment by achafetz** [comment]
Still running into an error which stops the whole code when I add in some test points to `rename_official()` 

https://github.com/ICPI/ICPIutilities/blob/88cbf91aa4da495a4153ca5e9e33eb5a51e196aa/R/rename_official.R#L24-L40

I developed a test RMD file that walks through a test function that contains `rename_official()` as part of the function, which can be found and run under the test_connection branch.

https://github.com/ICPI/ICPIutilities/blob/test_connection/NoInternetTesting.Rmd

**Comment by achafetz** [comment]
This actually ended up being resolved a while back. 

https://github.com/ICPI/ICPIutilities/blob/171809d1fa87727b89f97c8112e6ba252c365760/R/rename_official.R#L23-L31
