### ISSUE TITLE
Create a function for identifying the previous period

### ISSUE THREAD

**Issue by abeagedew** [ICPI/ICPIutilities#26]
It would be great if can have a function to identify the previous period, similar to the identifypd function.

**Comment by achafetz** [comment]
Done. I can update the code from `identify_pd()` to return the prior period. 

Will add the additional parameter `prior_pd = FALSE` as the default. When this is changed to `TRUE` it will return the prior period instead of the current one.

**Comment by abeagedew** [comment]
Awesome!!!

**Comment by abeagedew** [comment]
Thanks @achafetz

**Comment by achafetz** [comment]
`identifypd()` now has both requested features (identifying prior period and targets). Documentation is also updated on the [README](https://github.com/ICPI/ICPIutilities#identifypd)
