### ISSUE TITLE
Create a function to identify current target period

### ISSUE THREAD

**Issue by abeagedew** [ICPI/ICPIutilities#27]
It would be great if we can create a function to identify the current target period.

**Comment by achafetz** [comment]
I'll think about this one, but the current solution would be to use the lines of code below, extracting the year using `identifypd()` and then concatenating it with "fy" and "targets"

```
#identify current year
  curr_fy <- identifypd(df_mer, pd = "year")
#add targets onto year
  curr_target_pd <- paste0("fy",curr_fy, "_targets")
```
