### ISSUE TITLE
match_msd error on genie extract

### ISSUE THREAD

**Issue by wvp3** [ICPI/ICPIutilities#40]
A genie extract of the OU x IM dataset (downloaded on 11/6/2018) is producing the following error from match_msd:

Error in guess_header_(datasource, tokenizer, locale) : 
  Cannot read file \\cdc.gov/private/M327/wvp3/ICPI/Key pops TWG/DHIS2_e1627d1a4d504cc39fcaee3ca4fe950c.txt: This file is currently not available for use on this computer.
In addition: Warning messages:
1: In unzip(genie_filepath, exdir = extract_path) :
  write error in extracting from zip file
2: In file.info(x, extra_cols = FALSE) :
  cannot open file '\\cdc.gov/private/M327/wvp3/ICPI/Key pops TWG/DHIS2_e1627d1a4d504cc39fcaee3ca4fe950c.txt': This file is currently not available for use on this computer

**Comment by wvp3** [comment]
original command: 
ouxim <- ICPIutilities::match_msd("PEPFAR-Data-Genie-OUByIMs-2018-11-06.zip",to_lower=FALSE)

**Comment by achafetz** [comment]
@wvp3 looking at the your command, I have one thought as to where there might be an issue.  It's possible the zipped file is saved outside your working directory. If that's the case, you should try specifying the full file path to the zip file rather than just specifying the file name, eg ("C:/Users/[you]/[folder]/PEPFAR-Data-Genie-OUByIMs-2018-11-13.zip". Alternatively, you could change your working directory before running `match_msd()`, but that's probably less preferable.

Let me know if this resolves the issue.

**Comment by wvp3** [comment]
@achafetz The file was in the working directory the whole time -- but weirdly, I'm now getting a different issue (regardless of whether I include the path or not):

ouxim <- ICPIutilities::match_msd("\\\\cdc.gov/private/M327/wvp3/ICPI/Key pops TWG/PEPFAR-Data-Genie-OUByIMs-2018-11-06.zip",to_lower=FALSE)
Avoidable 9.328 seconds. This file is very unusual: it ends abruptly without a final newline, and also its size is a multiple of 4096 bytes. Please properly end the last row with a newline using for example 'echo >> file' to avoid this  time to copy.
Warning messages:
1: In unzip(genie_filepath, exdir = extract_path) :
  write error in extracting from zip file
2: In UseMethod("depth") :
  no applicable method for 'depth' applied to an object of class "NULL"
3: In data.table::fread(file, sep = "\t", colClasses = "character",  :
  Discarded single-line footer: <<Africa	KSkooYTy8FB	Zambia	f5RoebaDLMx	Zambia	Sq5c3WKfQWc	TBD	USAID	18487	TBD-GBV Follow on	MB10F6KgMle	HTS_SELF	N	DSD	HIVSelfTestUser	HIVSelfTestUser	"loZmPoGpvEZ                 "	Unassisted - Sex Partner		Incompatible Age>>
4: In UseMethod("depth") :
  no applicable method for 'depth' applied to an object of class "NULL"'

Is match_msd() working for you on the ouxim zip file extract?

**Comment by achafetz** [comment]
Hmm. Lots of warning messages. I have texted out an OUxIM this morning it worked like a charm.  It's finding the file it looks like, but its unclear what the write error is when extracting. 

Send me the file zipped file and I can chekc it out on my machine. And we can troubleshoot when you're at ICPI.

Test with a Genie output:
``` r
genie_filepath <- "C:/Users/achafetz/Downloads/PEPFAR-Data-Genie-OUByIMs-2018-11-13.zip"
ICPIutilities::match_msd(genie_filepath, to_lower = FALSE, save_rds = FALSE)
#> # A tibble: 169 x 39
#>    Region RegionUID OperatingUnit OperatingUnitUID CountryName mechanismUID
#>    <chr>  <chr>     <chr>         <chr>            <chr>       <chr>       
#>  1 Africa KSkooYTy~ Malawi        lZsCb6y0KDX      Malawi      dtZlbDWpRfe 
#>  2 Africa KSkooYTy~ Malawi        lZsCb6y0KDX      Malawi      dtZlbDWpRfe 
#>  3 Africa KSkooYTy~ Malawi        lZsCb6y0KDX      Malawi      dtZlbDWpRfe 
#>  4 Africa KSkooYTy~ Malawi        lZsCb6y0KDX      Malawi      dtZlbDWpRfe 
#>  5 Africa KSkooYTy~ Malawi        lZsCb6y0KDX      Malawi      dtZlbDWpRfe 
#>  6 Africa KSkooYTy~ Malawi        lZsCb6y0KDX      Malawi      dtZlbDWpRfe 
#>  7 Africa KSkooYTy~ Malawi        lZsCb6y0KDX      Malawi      dtZlbDWpRfe 
#>  8 Africa KSkooYTy~ Malawi        lZsCb6y0KDX      Malawi      dtZlbDWpRfe 
#>  9 Africa KSkooYTy~ Malawi        lZsCb6y0KDX      Malawi      dtZlbDWpRfe 
#> 10 Africa KSkooYTy~ Malawi        lZsCb6y0KDX      Malawi      dtZlbDWpRfe 
#> # ... with 159 more rows, and 33 more variables: PrimePartner <chr>,
#> #   FundingAgency <chr>, MechanismID <chr>,
#> #   ImplementingMechanismName <chr>, indicator <chr>,
#> #   numeratorDenom <chr>, indicatorType <chr>, disaggregate <chr>,
#> #   standardizedDisaggregate <chr>, categoryOptionComboName <chr>,
#> #   AgeAsEntered <chr>, AgeFine <chr>, AgeSemiFine <chr>, AgeCoarse <chr>,
#> #   Sex <chr>, resultStatus <chr>, otherDisaggregate <chr>,
#> #   coarseDisaggregate <chr>, modality <chr>, isMCAD <chr>,
#> #   FY2017_TARGETS <dbl>, FY2017Q1 <dbl>, FY2017Q2 <dbl>, FY2017Q3 <dbl>,
#> #   FY2017Q4 <dbl>, FY2017APR <dbl>, FY2018_TARGETS <dbl>, FY2018Q1 <dbl>,
#> #   FY2018Q2 <dbl>, FY2018Q3 <dbl>, FY2018Q4 <dbl>, FY2018APR <dbl>,
#> #   FY2019_TARGETS <dbl>
```

<sup>Created on 2018-11-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by achafetz** [comment]
@wvp3, is this still an issue?
