### ISSUE TITLE
Addition of SNU2 to Site by MSD dataset

### ISSUE THREAD

**Issue by shazadahmed10** [ICPI/ICPIutilities#48]
Requester: Leigh Tally
Request: To add SNU2 as a new column to the Q4 Site by MSD dataset for Rwanda. Follow up request to add the same column to the in-process Rwadna MSD as well.
Status: Completed for the Q4 MSD by Shazad. Used the DATIM org hierarchy dataset circulated by Josh. Took SNU2 and orgunituid from org hierarchy file and merged OrgUnitUID to the Site by IM MSD. Sent the updated MSD directly to Leigh.

Table where there is another level between PSNU and Community, posted by Pooja:
![snu2 table](https://user-images.githubusercontent.com/8259381/52574901-3f0ea680-2deb-11e9-91c4-e0c9479ceada.JPG)

Final Script Posted HERE
--

Final Rwanda Product Posted on SP Here
--

**Comment by shazadahmed10** [comment]
Update: Request for same addition, but to the in-process Rwanda dataset

**Comment by jb3436** [comment]
This issue was copied to ICPI/DAQ#52

**Comment by achafetz** [comment]
@shazadahmed10, you mentioned you already had a script for this. If so, can you do a pull request to submit it?

**Comment by achafetz** [comment]
Closing unless there are other comments from @shazadahmed10  or @jb3436
