### ISSUE TITLE
Issues reading ICPI dataset

### ISSUE THREAD

**Issue by Green-EyE** [ICPI/ICPIutilities#49]
Hi ALL

read_tsv and read_msd are not been recognized, please advise

Thanks
Cicero

**Comment by achafetz** [comment]
Please provide the [`reprex`](https://reprex.tidyverse.org/) or code you were using.

Also note that `read_tsv()` is not part of the `ICPIutilities` package. 

What is the error message you get when you run `read_msd()`?

**Comment by Green-EyE** [comment]
Error: could not find function "read_tsv"
Error: could not find function "read_msd"

Even after I load the tidyverse library

**Comment by Green-EyE** [comment]
Also I tried this, its failing :

SITE_IM_FY17_18 <- read.delim("C:/ICPI_MER_Structured_Dataset_SITE_IM_FY17-18_Mozambique_20180515_v1_1.txt")
 
hts <- filter(SITE_IM_FY17_18, indicator =="HTS_TST")
Error in filter(SITE_IM_FY17_18, indicator == "HTS_TST") : 
  object 'indicator' not found

**Comment by achafetz** [comment]
Did you load the `ICPIutiltites` package? I just ran `read_msd()` successfully on the Moz site file

``` r
library(ICPIutilities)

df_moz <- read_msd("../Downloads/MER_Structured_Dataset_Site_IM_FY17-19_20190215_v1_2_Mozambique.txt")

```

**Comment by Green-EyE** [comment]
Hi Aaron
Seems that the issue is with installation of ICPIutilities, I'm using the following code lines :
install.packages("devtools")
devtools::install_github("ICPI/ICPIutilities")

Error in loadNamespace(name) : there is no package called ‘devtools’

Please advise

Thanks
Cicero

**Comment by Green-EyE** [comment]
The following code worked perfectly, thanks for your support :


library(dplyr)

setwd("~/Documents/ICPI/ICPI_MER_Structured_Dataset_SITE_IM_FY17-18_Mozambique_20180515_v1_1")
SITE_IM_FY17_18 <- read.delim2("~/Documents/ICPI/ICPI_MER_Structured_Dataset_SITE_IM_FY17-18_Mozambique_20180515_v1_1/ICPI_MER_Structured_Dataset_SITE_IM_FY17-18_Mozambique_20180515_v1_1.txt")
View(SITE_IM_FY17_18)

hts <- filter(SITE_IM_FY17_18, indicator =="HTS_TST")
View(hts)
hts2 <- filter(SITE_IM_FY17_18, indicator =="HTS_TST_NEG" | indicator =="HTS_TST_POS" )
View(hts2)

PMTCT <- filter(SITE_IM_FY17_18, indicator =="PMTCT_ART"|indicator =="PMTCT_CTX"|indicator =="PMTCT_EID"|
                  indicator =="PMTCT_EID_Less_Equal_Two_Months"|indicator =="PMTCT_EID_POS"|indicator =="PMTCT_EID_POS_12MO"|
                  indicator =="PMTCT_EID_POS_2MO"|indicator =="PMTCT_EID_Two_Twelve_Months" |indicator =="PMTCT_HEI_POS"|indicator =="PMTCT_STAT"|
                  indicator =="PMTCT_STAT_KnownatEntry_POSITIVE" |indicator =="PMTCT_STAT_NewlyIdentified_Negative"|indicator =="PMTCT_STAT_NewlyIdentified_POSITIVE"|
                  indicator =="PMTCT_STAT_POS")

View(PMTCT)
TX <- filter(SITE_IM_FY17_18, indicator == "TX_NEW" |indicator == "TX_CURR" |indicator == "TX_PVLS" |indicator == "TX_RET")
View(TX)


write.csv(hts, "SITE_IM_FY17_18_HTS_TST.csv")
write.csv(hts2, "SITE_IM_FY17_18_HTS_TST_NEG&POS.csv")
write.csv(PMTCT, "SITE_IM_FY17_18_PMTCT.csv")
write.csv(TX, "SITE_IM_FY17_18_TX.csv")
