### ISSUE TITLE
Contributing to a package

### ISSUE THREAD

**Issue by achafetz** [ICPI/ICPIutilities#50]
First off, thanks for making a contribution to the `ICPIutilties` package. Unfortunately, your code broke the package, so I had to rebase the package off the prior commit it for now.

![image](https://user-images.githubusercontent.com/8933069/55352171-3e5ecc00-548e-11e9-91b3-cd40b9fd9f69.png)

**R Package Contributions**
I think it would be good to add it back in as others may find this useful. Unlike regular scripts, a package requires some unique processing to make it function across people's machines. For instance, you will need to remove any additional text/code outside the function itself other than the roxygen comments and you will need to specify any non-base R function, e.g. `dplyr::mutate()` instead of just `mutate()`. I like that you included some error handling in the function. I would check out [Jenny Bryan's Code Smells and Feels](https://speakerdeck.com/jennybc/code-smells-and-feels) talk where there are some good examples about including error handling in functions.

I would recommend reading [Hadley's Package book](http://r-pkgs.had.co.nz/) for an understanding of how packages are formulated and maintained. I would also recommend checking out [this post](https://r-mageddon.netlify.com/post/writing-an-r-package-from-scratch/) which updates [Hillary Parker's post](https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/) on writing an R package.

**Contributing on GitHub**
It is also worth mentioning that when collaborating with git/GitHub, the best practice is to build branches (rather than working in the master of the repo) and then submit those back for approval, which is called a pull request. The way this works is if you want to propose an enchancement/change/etc to another repo, you first `fork` that repo, create a new `branch` to work on, and the submit a `pull request` when you want to submit the new code. I've outlined it in [DIV presentation](https://github.com/ICPI/DIV/raw/master/Presentations/GitHub%20Workshops/GitHub%20Workshop%2020180809.pdf) and you can read more on the process at [Happy Git and GitHub for the useR](https://happygitwithr.com/). 

![image](https://user-images.githubusercontent.com/8933069/55353256-d8c00f00-5490-11e9-8c4a-b72d2cca7520.png)

If you have questions, let me know and I can help you through the process.

**Comment by wvp3** [comment]
> Unlike regular scripts, a package requires some unique processing to make it function across people's machines. For instance...
Yeah, I will need a little assistance from the DIV here with additional specific steps comprising the "unique processing" you are referring to.  The reading material you linked is pretty jargon-y for a non-developer so I couldn't easily tell (in practical terms) what I need to do.

**Comment by achafetz** [comment]
Sure thing. I'll be at ICPI Friday if you want to drop by for help.  In the interim, I would recommend reading over the resources above. I have also written out the process, step by step.

The key things as I see it are the following:
1) Fork this repo (ie make a copy to your GitHub account)
1) Create a new branch (kp_group_enchancement)
1) Clone it to your computer (ie download)
1) Open the Project in RStudio
1) Install `devtools` and `usethis` and load both
1) Load the `ICPIutlitites` package (`Ctrl + Shift + L`)
1) In your script, remove all the text above `genpop <- function(df) {`
1) In your script, remove `require(tidyverse)`
1) Rename your function. Best practice is for functions should typically be verbs, eg `calc_genpop()`, and describe what the function is doing to the object, eg the data frame
1) In your script, before every non-base R function, specify which package its from (eg `filter()` -> `dplyr::filter()`, and `case_when()` -> `dplyr::case_when()`
1) Add in `roxygen` comments (`Ctrl + Alt + Shift + R`), adding in the title and describe what df is and what the user should enter here (eg should run `read_msd()` first). You will need to add that you are relying on piping (`#' @importFrom dplyr %>%`). Delete the `@return` line as well as the `@example` line.
1) Document the information to go into the help file (`Ctrl + Shift + D`). This will be what you entered in the Roxygen comments
1) Build/install the package on your computer (`Ctrl + Shift + B`)
1) Restart R (`Ctrl + Shift + F10`). Load the piping `library(magrittr)` and test to see, also seeing if your function works without any of the other packages loaded (they should since you have made all the functions explicit).
1) Update the README to include information on the purpose of the function and how to use it.
1) In your git IDE (eg R, GitHub Desktop, GitKraken, etc), commit your changes to your forked branch
1) From GitHub online, create a pull request from [this repo](https://github.com/ICPI/ICPIutilities/pulls) or your fork, and then assign it to me for review. Once it passes Travis CI, I can then integrate it into the package.

**Comment by wvp3** [comment]
looping in others who may be interested in learning about the needed steps.

**Comment by achafetz** [comment]
moved this to the [wiki](https://github.com/ICPI/ICPIutilities/wiki/Contributing-to-a-Package). closing issue
